repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
  
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    - id: black
      language_version: python3.11

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        files: ^source/
        types: [file, python]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    name: mypy
    entry: mypy
    language: system
    types: [python]