AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role and SageMaker User Profile for Cost Optimization Blog'

Parameters:
  CURRoleName:
    Type: String
    Description: The name of the new Cost & Usage Reports IAM Role
    Default: SageMakerCostUsageReportsRole
  UserProfileName:
    Type: String
    Description: The name of the new Cost & Usage Reports User Profile
    Default: studio-cur-user-profile

Resources:

  CURS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "cur-bucket-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CURGlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: cur_database

  CURGlueCrawlerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'glue.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub "arn:aws:s3:::cur-bucket-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::cur-bucket-${AWS::AccountId}"

  CURGlueCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: !GetAtt CURGlueCrawlerRole.Arn
      DatabaseName: !Ref CURGlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub "s3://cur-bucket-${AWS::AccountId}/sagemaker-cur/"
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)'
      TablePrefix: cur_

  AthenaWorkGroup:
    Type: 'AWS::Athena::WorkGroup'
    Properties:
      Name: AthenaWorkGroup
      Description: "WorkGroup for CUR Athena Queries"
      State: ENABLED
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: true
        RequesterPaysEnabled: false
        ResultConfiguration:
          OutputLocation: !Sub "s3://cur-bucket-${AWS::AccountId}/athena-results/"

  QuickSightIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'quicksight.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: QuickSightAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource:
                  - !Sub "arn:aws:s3:::cur-bucket-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::cur-bucket-${AWS::AccountId}"
              - Effect: 'Allow'
                Action:
                  - 'athena:StartQueryExecution'
                  - 'athena:GetQueryResults'
                  - 'athena:ListQueryExecutions'
                Resource:
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/AthenaWorkGroup"
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:query/*"
              - Effect: 'Allow'
                Action:
                  - 'glue:GetTable'
                  - 'glue:GetTableVersion'
                  - 'glue:GetTableVersions'
                  - 'glue:GetDatabase'
                Resource:
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/cur_database"
                  - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/cur_database/*"

  SageMakerCostUsageReportsRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: !Ref CURRoleName
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - 'sagemaker.amazonaws.com'
                - 'athena.amazonaws.com'
                - 'quicksight.amazonaws.com'
                - 's3.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies: 

        - PolicyName: 'AthenaAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'athena:StartQueryExecution'
                  - 'athena:GetQueryResults'
                  - 'athena:ListQueryExecutions'
                Resource: 
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/*"
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:query/*"

        - PolicyName: 'QuickSightAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'quicksight:Describe*'
                  - 'quicksight:List*'
                Resource: 
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:user/${AWS::AccountId}/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:dataset/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:analysis/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:dashboard/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:namespace/default"

        - PolicyName: 'CURAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'cur:DescribeReportDefinitions'
                  - 'cur:GetReportData'
                Resource: 
                  - !Sub "arn:aws:cur:${AWS::Region}:${AWS::AccountId}:report/*"

        - PolicyName: 'S3AccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: arn:aws:s3:::*

        - PolicyName: 'CostExplorerAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'ce:GetCostAndUsage'
                  - 'ce:GetCostForecast'
                  - 'ce:GetReservationUtilization'
                  - 'ce:GetSavingsPlansUtilization'
                  - 'ce:DescribeCostCategoryDefinition'
                Resource: 
                  - "*"

        - PolicyName: 'BudgetsAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'budgets:ViewBudget'
                  - 'budgets:ModifyBudget'
                Resource: 
                  - !Sub "arn:aws:budgets::${AWS::AccountId}:budget/*"

        - PolicyName: 'SageMakerCanvasDenyPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Deny'
                Action: 
                  - 'sagemaker:CreateCanvasApp'
                  - 'sagemaker:DeleteCanvasApp'
                  - 'sagemaker:ListCanvasApp'
                  - 'sagemaker:DescribeCanvasApp'
                  - 'sagemaker:InvokeCanvasApp'
                  - 'sagemaker:StartCanvasApp'
                  - 'sagemaker:StopCanvasApp'
                Resource: 
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:canvas-app/*"

  SageMakerUserProfile:
    Type: 'AWS::SageMaker::UserProfile'
    Properties:
      DomainId: !ImportValue SageMakerDomainId
      UserProfileName: !Ref UserProfileName
      UserSettings:
        ExecutionRole: !GetAtt SageMakerCostUsageReportsRole.Arn

Outputs:
  SageMakerCostUsageReportsRoleARN:
    Description: 'ARN of the IAM role for SageMaker cost usage reports'
    Value: !GetAtt SageMakerCostUsageReportsRole.Arn
  SageMakerUserProfileName:
    Description: 'Name of the SageMaker User Profile for cost optimization'
    Value: !Ref SageMakerUserProfile
