AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role and SageMaker User Profile for Cost Optimization Blog'

Parameters:
  UserProfileName:
    Type: String
    Description: The name of the new Cost & Usage Reports User Profile
    Default: studio-cur-user-profile

Resources:
  SageMakerCostUsageReportsRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: 'SageMakerCostUsageReportsRole'
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: 'Allow'
            Principal: 
              Service: 
                - 'sagemaker.amazonaws.com'
                - 'athena.amazonaws.com'
                - 'quicksight.amazonaws.com'
                - 's3.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies: 
        - PolicyName: 'SageMakerCommonActionsPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'sagemaker:List*'
                  - 'sagemaker:Describe*'
                  - 'sagemaker:InvokeEndpoint'
                Resource: 
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*"

        - PolicyName: 'AthenaAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'athena:StartQueryExecution'
                  - 'athena:GetQueryResults'
                  - 'athena:ListQueryExecutions'
                Resource: 
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/*"
                  - !Sub "arn:aws:athena:${AWS::Region}:${AWS::AccountId}:query/*"

        - PolicyName: 'QuickSightAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'quicksight:Describe*'
                  - 'quicksight:List*'
                Resource: 
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:user/${AWS::AccountId}/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:dataset/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:analysis/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:dashboard/*"
                  - !Sub "arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:namespace/default"

        - PolicyName: 'CURAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'cur:DescribeReportDefinitions'
                  - 'cur:GetReportData'
                Resource: 
                  - !Sub "arn:aws:cur:${AWS::Region}:${AWS::AccountId}:report/*"

        - PolicyName: 'S3AccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: 
                  - !Sub "arn:aws:s3:::your-s3-bucket-name/*"
                  - !Sub "arn:aws:s3:::your-s3-bucket-name"

        - PolicyName: 'CostExplorerAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'ce:GetCostAndUsage'
                  - 'ce:GetCostForecast'
                  - 'ce:GetReservationUtilization'
                  - 'ce:GetSavingsPlansUtilization'
                  - 'ce:DescribeCostCategoryDefinition'
                Resource: 
                  - "*"

        - PolicyName: 'BudgetsAccessPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Allow'
                Action: 
                  - 'budgets:ViewBudget'
                  - 'budgets:ModifyBudget'
                Resource: 
                  - !Sub "arn:aws:budgets::${AWS::AccountId}:budget/*"

        - PolicyName: 'SageMakerCanvasDenyPolicy'
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: 'Deny'
                Action: 
                  - 'sagemaker:CreateCanvasApp'
                  - 'sagemaker:DeleteCanvasApp'
                  - 'sagemaker:ListCanvasApp'
                  - 'sagemaker:DescribeCanvasApp'
                  - 'sagemaker:InvokeCanvasApp'
                  - 'sagemaker:StartCanvasApp'
                  - 'sagemaker:StopCanvasApp'
                Resource: 
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:canvas-app/*"

        - PolicyName: 'SageMakerStudioAppPermissionsPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Effect: Allow
                Action:
                  - sagemaker:CreateApp
                  - sagemaker:DeleteApp
                Resource: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:app/*"
                Condition:
                  "Null":
                    "sagemaker:OwnerUserProfileArn": "true"
              - 
                Effect: Allow
                Action:
                  - sagemaker:CreatePresignedDomainUrl
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:sagemaker:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':user-profile/${sagemaker:DomainId}/${sagemaker:UserProfileName}'
              - 
                Effect: Allow
                Action:
                  - sagemaker:ListApps
                  - sagemaker:ListDomains
                  - sagemaker:ListUserProfiles
                  - sagemaker:ListSpaces
                  - sagemaker:DescribeApp
                  - sagemaker:DescribeDomain
                  - sagemaker:DescribeUserProfile
                  - sagemaker:DescribeSpace
                Resource: "*"
              - 
                Effect: Allow
                Action:
                  - sagemaker:AddTags
                Resource: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*/*"
                Condition:
                  "Null":
                    "sagemaker:TaggingAction": "false"
              - 
                Effect: Allow
                Action:
                  - sagemaker:CreateSpace
                  - sagemaker:UpdateSpace
                  - sagemaker:DeleteSpace
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:sagemaker:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':space/${sagemaker:DomainId}/*'
                Condition:
                  "Null":
                    "sagemaker:OwnerUserProfileArn": "true"
              - 
                Effect: Allow
                Action:
                  - sagemaker:CreateSpace
                  - sagemaker:UpdateSpace
                  - sagemaker:DeleteSpace
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:sagemaker:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':space/${sagemaker:DomainId}/*'
                Condition:
                  ArnLike:
                    "sagemaker:OwnerUserProfileArn": 
                      !Join
                        - ''
                        - - 'arn:aws:sagemaker:'
                          - !Ref 'AWS::Region'
                          - ':'
                          - !Ref 'AWS::AccountId'
                          - ':user-profile/${sagemaker:DomainId}/${sagemaker:UserProfileName}'
                  StringEquals:
                    "sagemaker:SpaceSharingType":
                      - "Private"
                      - "Shared"
              - 
                Effect: Allow
                Action:
                  - sagemaker:CreateApp
                  - sagemaker:DeleteApp
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:sagemaker:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':app/${sagemaker:DomainId}/*'
                Condition:
                  ArnLike:
                    "sagemaker:OwnerUserProfileArn":
                      !Join
                        - ''
                        - - 'arn:aws:sagemaker:'
                          - !Ref 'AWS::Region'
                          - ':'
                          - !Ref 'AWS::AccountId'
                          - ':user-profile/${sagemaker:DomainId}/${sagemaker:UserProfileName}'
                  StringEquals:
                    "sagemaker:SpaceSharingType":
                      - "Private"
              - 
                Effect: Deny
                Sid: DenySageMakerCanvasCreateApp
                Action:
                  - sagemaker:CreateApp
                Resource:
                  !Join
                    - ''
                    - - 'arn:aws:sagemaker:'
                      - !Ref 'AWS::Region'
                      - ':'
                      - !Ref 'AWS::AccountId'
                      - ':app/${sagemaker:DomainId}/${sagemaker:UserProfileName}/canvas/*'
              - 
                Effect: Allow
                Action:
                  - sagemaker:CreateApp
                  - sagemaker:DeleteApp
                Resource: "arn:aws:sagemaker:*:*:app/${sagemaker:DomainId}/*/*/*"
                Condition:
                  StringEquals:
                    "sagemaker:SpaceSharingType":
                      - "Shared"

  SageMakerUserProfile:
    Type: 'AWS::SageMaker::UserProfile'
    Properties:
      DomainId: !ImportValue SageMakerDomainId
      UserProfileName: !Ref UserProfileName
      UserSettings:
        ExecutionRole: !GetAtt SageMakerCostUsageReportsRole.Arn

Outputs:
  SageMakerCostUsageReportsRoleARN:
    Description: 'ARN of the IAM role for SageMaker cost usage reports'
    Value: !GetAtt SageMakerCostUsageReportsRole.Arn
  SageMakerUserProfileName:
    Description: 'Name of the SageMaker User Profile for cost optimization'
    Value: !Ref SageMakerUserProfile
