name: Pre-commit and Validate CloudFormation templates

on:
  push:
    branches:
      - 'mccartni/*'
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python for cfn-lint
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install cfn-lint and pre-commit
      - name: Install CFN Lint and Pre-commit
        run: |
          pip install cfn-lint pre-commit
          pre-commit install

      # Run pre-commit hooks
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      # Run cfn-lint on CloudFormation templates
      - name: Lint CloudFormation Templates
        run: |
          for file in $(find . -type f -name '*.yaml' -path './src-cloudformation*/*'); do
            cfn-lint "$file" --ignore-checks W || echo "Linting found non-critical issues in $file"
          done
